In [7]:
import numpy as np
import numpy.linalg as npla

### <u>Part 1 : Matrices and Vectors in Python</U>

In Python both matrices and vectors are defined as numpy arrays (np.array). A numpy array 

#### Consider a random matrix of dimensions (3, 4)

In [23]:
# Define random matrix of size (3, 4)
A = np.random.rand(3, 4) 
A

array([[0.23974787, 0.60437791, 0.13142659, 0.37842571],
       [0.26071109, 0.65788916, 0.01327057, 0.86411454],
       [0.30197165, 0.83024751, 0.14300021, 0.5171466 ]])

In [32]:
# Getting the dimensions (called "shape" in python lingo) 
A_dims = A.shape
n_rows = A_dims[0]
n_cols = A_dims[1]

print("Dimensions of array A:", A_dims)
print("Number rows of array A:", A_dims)
print("Number of columns of array A:", A_dims)

Dimensions of array A: (3, 4)
Number rows of array A: (3, 4)
Number of columns of array A: (3, 4)


### <u>Part 1 : Solving Linear equations</U>

In engineering, you will run into various scenarios where you will have to solve for a vector $x \in \mathbb{R}^{n}$ in equations such as 

$$ 
\mathbf{A} x = b
$$

Here, $\mathbf{A} \in \mathbb{R}^{n \times n}$ and $b \in \mathbb{R}^{n}$ respectively. What you're looking at is a <i>system of linear equations</i>. Let us look at an examle by generating random $\mathbf{A}$ and $b$ for $n = 5$ - 


In [22]:
A = np.random.rand(5,5)
b = np.random.rand(5)

print("A=\n", A)
print("b=\n", b)

A=
 [[0.7508889  0.39909641 0.85473418 0.74605117 0.73225394]
 [0.3856509  0.24321184 0.01662001 0.55318124 0.84294132]
 [0.02952536 0.62477427 0.75466997 0.63127906 0.47129999]
 [0.88346628 0.22183041 0.83453967 0.13870635 0.13251057]
 [0.56028335 0.57216218 0.78825358 0.13817955 0.05401819]]
b=
 [0.87017695 0.56499835 0.24374936 0.06342172 0.50860741]


Before we talk about solving the equations, let us talk about inverse first. The inverse of a matrix $\mathbf{A}$, as denoted by $\mathbf{A}^{-1}$, is a matrix that satisfies the following condition
$$
\mathbf{A} \mathbf{A}^{-1} = \mathbf{A}^{-1} \mathbf{A} = \mathbf{I},
$$
where $\mathbf{I}$ is the identity matrix. 