In [1]:
import numpy as np 

# Section 2

1. (Review) Linear systems (Ax = b) and error
2. Array slicing and manipulation
3. Symmetric matrices
4. Permutations 



### <u><b>Linear system</b></u> 
A linear system is of the following form, 
$$
A x = b. \\ 
$$

The goal is to solve for the vector $x$, given the matrix $A$ and the vector $b$. Let us make up a random example and use the tools python gives us to solve it!

In [2]:
# Consider a random example of a linear system 
A = np.random.rand(3, 3) 
x = np.random.rand(3)      # true solution 
b = A @ x

print("A: \n", A)
print("x: \n", x)
print("b: \n", b)

A: 
 [[0.2794836  0.74239139 0.0180318 ]
 [0.01341511 0.85416331 0.92952869]
 [0.58126511 0.80373372 0.30415627]]
x: 
 [0.65949042 0.86146338 0.8560225 ]
b: 
 [0.83929537 1.54037502 1.33609056]


## Solving the linear system (what happens behind np.linalg.solve)

Consider the <i>inverse</i> of $A$, denoted as $A^{-1}$, which is a matrix that satisfies the following condition 
$$
A^{-1}A = AA^{-1} = I.
$$
The solution is computed by multiplaying the linear system with the inverse on both sides
$$
A^{-1}Ax = A^{-1}b \\ 
$$
$$
x = A^{-1}b.
$$
If you remember from your linear algebra course, this only works for full-rank matrices. You can implement this yourself, but it is recommended to use the numpy solver (it is faster).

In [3]:
x_approx_der   = np.linalg.inv(A) @ b   # derived solution
x_approx_npy   = np.linalg.solve(A, b)  # numpy method

print("\n derived soln (np.linalg.inv(A) @ b): \n", x_approx_der)
print("\n numpy soln np.linalg.solve(A, b) (recommended):   \n", x_approx_npy)


 derived soln (np.linalg.inv(A) @ b): 
 [0.65949042 0.86146338 0.8560225 ]

 numpy soln np.linalg.solve(A, b) (recommended):   
 [0.65949042 0.86146338 0.8560225 ]


## <b><u>Computing error</u></b>

Let $x'$ be an approximation of $x$ computed as shown above. The <i> residual vector </i> $r$is the difference between $x$ and $x'$ (in this case $r = x' - x$). Consider the $L_2$ norm.

$$
|| x ||_2 = \left( \sum_{i} |x_i|^2 \right)^{\frac{1}{2}}
$$

1. <b> Absolute Error </b>: Measures difference between actual value and computed value. Interpreted as distance in Euclidean space. 
   $$ ||r||_2 = || x - x' ||_2 $$
2. <b> Relative Error </b>: Absolute error normalized by the norm of the actual value. 
   $$ \frac{|| x - x' ||_2}{|| x ||_2} $$


In [24]:
res_vec = x_approx_npy - x
abs_err = np.linalg.norm(res_vec) 
rel_err = np.linalg.norm(res_vec) / np.linalg.norm(x)

print("Absolute Error: ", abs_err)
print("Relative Error: ", rel_err)

Absolute Error:  7.771561172376096e-16
Relative Error:  5.623567394213557e-16


## <b><u>Array Slicing</u></b>


Matrices can be accessed and manipulated in many ways. This is an incredibly useful tool to efficiently manipulate the rows of matrices for methods such as Gaussian elem. 

Let us construct a simple matrix as shown below 

In [21]:
A = np.arange(0, 25).reshape(5, 5) 
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

To access the $m^{th}$ row and $n^{th}$ column, the syntax is A\[m-1, n-1\] or A\[m-1\]\[n-1\]

In [22]:
# Access the element on the second row and third column
print("second row, third column: ", A[1, 2])
print("third row, second column: ", A[2, 1])
print("fifth row, third column:  ", A[4, 2])
print("fourth row, first column: ", A[3, 0])

second row, third column:  7
third row, second column:  11
fifth row, third column:   22
fourth row, first column:  15


You can also access more than one values and get a new array. The syntax for doing so is the same as before but we use the slice (:) operator to access more than one value. Some examples to show how it's used - 

1. A\[i, :\] retrieves the entire $i^{th}$ row (notice how we are specifying the row index, but using the : operator to specify the number of column elements to consider.
2. A\[:, i\] retrieves the entire $i^{th}$ column.
3. A\[0:3, 0:3\] retrieves the top left 3x3 matrix block from A. 

In [23]:
first_row            = A[0, :]
first_col            = A[:, 0]
first_row_three_vals = A[3, 0:3]
top_left_3x3_matrix  = A[0:3, 0:3]
center_3x3_matrix    = A[1:4, 1:4]
specified_sub_matrix = A[[0, 3], :]

print("\n full matrix A: \n", A)
print("\n first row A[0, :]: \n", first_row)
print("\n first col A[:, 0]: \n", first_col)
print("\n the first three elements of the third row A[3, 0:3]: \n", first_row_three_vals)
print("\n top left 3x3 matrix A[0:3, 0:3]: \n", top_left_3x3_matrix)
print("\n center 3x3 matrix A[1:4, 1:4]: \n", center_3x3_matrix)
print("\n You can also pass in lists to specify which rows/cols to fetch (eg. To slice rows 1 and 3 - A[[1, 3], :]): \n", specified_sub_matrix)




 full matrix A: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

 first row A[0, :]: 
 [0 1 2 3 4]

 first col A[:, 0]: 
 [ 0  5 10 15 20]

 the first three elements of the third row A[3, 0:3]: 
 [15 16 17]

 top left 3x3 matrix A[0:3, 0:3]: 
 [[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]

 center 3x3 matrix A[1:4, 1:4]: 
 [[ 6  7  8]
 [11 12 13]
 [16 17 18]]

 You can also pass in lists to specify which rows/cols to fetch (eg. To slice rows 1 and 3 - A[[1, 3], :]): 
 [[ 0  1  2  3  4]
 [15 16 17 18 19]]


You can also set multiple values at once with an array similarly as above. For example to set an entire row to zero.

In [13]:
# set first rows to 3
print("\n original matrix: \n", A)

A[0, :] = 3           
print("\n set the entire row to 3 (A[0, :] = 3): \n", A)

# set the first two elements of the second row with [1, 7]
A[1, 0:2] = [1, 7]        
print("\n set the first two elements of the second row as [1, 7] (A[1, 0:2] = [1, 7] ) : \n", A)

# set the bottom right 3x3 block to a 3x3 identity matrix
A[2:5, 2:5] = np.eye(3)
print("\n set the bottom right 3x3 block to identity (A[2:5, 2:5] = np.eye(3)): \n", A)

# perform the row operation r_2 = 3*r1 - r2
A[1, :] = 3*A[0, :] - A[1, :]
print("\n perform the row operation r2 = r*r1 - r2 (A[1, :] = 3*A[0, :] - A[1, :]): \n", A)


 original matrix: 
 [[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]]

 set the entire row to 3 (A[0, :] = 3): 
 [[3. 3. 3. 3. 3.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]]

 set the first two elements of the second row as [1, 7] (A[1, 0:2] = [1, 7] ) : 
 [[3. 3. 3. 3. 3.]
 [1. 7. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]]

 set the bottom right 3x3 block to identity (A[2:5, 2:5] = np.eye(3)): 
 [[3. 3. 3. 3. 3.]
 [1. 7. 2. 2. 2.]
 [3. 3. 1. 0. 0.]
 [4. 4. 0. 1. 0.]
 [5. 5. 0. 0. 1.]]

 perform the row operation r2 = r*r1 - r2 (A[1, :] = 3*A[0, :] - A[1, :]): 
 [[3. 3. 3. 3. 3.]
 [8. 2. 7. 7. 7.]
 [3. 3. 1. 0. 0.]
 [4. 4. 0. 1. 0.]
 [5. 5. 0. 0. 1.]]


# Permutations

Flipping specific rows (or columns) of a matrix is referred to as permutations. 

In [8]:
#Let us construct a matrix as follows by stacking the vectors [1 1 1 1 1], [2 2 2 2 2] ... [5 5 5 5 5]
A = np.array([   np.ones(5), 
               2*np.ones(5), 
               3*np.ones(5), 
               4*np.ones(5), 
               5*np.ones(5)  ])
A

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [9]:
# A permutation is an operation that flips the rows or columns of a matrix. This is done using permutation matrices.
# For a matrix A and a permutation matrix P, the operation PA would flip a specific row and col of A. 
print("\n Original matrix (A): \n", A)

# simplest permutation matrix : the identity matrix! which does no flipping. 
I = np.eye(5) 

# the permutation matrices are formed by flipping a specific rows (or cols) of the identity matrix that you want 
# in this case, we will construct a permutation matrix that flips rows 2 and 3 
P1 = np.eye(5)
P1[1, :] = I[2, :]
P1[2, :] = I[1, :]
print("\n Permutation matrix to switch rows 2 and 3 (P1): \n", P1)

# this permutation matrix will flip rows 2 and 3 of the matrix A-
A = P1 @ A
print("\n Permuted matrix (P1 @ A): \n", A)

# applying the permutation again, we flip it back
A = P1 @ A
print("\n Apply permutation again to flip it back (P1 @ A): \n", A)


 Original matrix (A): 
 [[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]]

 Permutation matrix to switch rows 2 and 3 (P1): 
 [[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

 Permuted matrix (P1 @ A): 
 [[1. 1. 1. 1. 1.]
 [3. 3. 3. 3. 3.]
 [2. 2. 2. 2. 2.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]]

 Apply permutation again to flip it back (P1 @ A): 
 [[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]]


In [14]:
# for an nxn matrix, there are n! possible permutations, 
# for a matrix of size 2 there are 2! = 1 possible permutations 
# Let us print out the permutation matrices for a 5x5 matrix

print("\nAll possible permutation matrices for 5x5 matrices")
# permutation matrices to flip rows
I = np.eye(3)
for i in range(3):
    for j in range(i+1, 3):
        P1 = np.eye(3)
        P1[i, :] = I[j, :]
        P1[j, :] = I[i, :]
        print(f"\n P to flip row {i+1} and {j+1}: \n {P1}")

# permutation matrices to flip cols
print("\n The same can be done for columns! Just do the same thing column wise (eg. flip I[:, 1] and I[:, 2])")
for i in range(3):
    for j in range(i+1, 3):
        P1 = np.eye(3)
        P1[:, i] = I[:, j]
        P1[:, j] = I[:, i]
        print(f"\n P to flip col {i+1} and {j+1}: \n {P1}")


All possible permutation matrices for 5x5 matrices

 P to flip row 1 and 2: 
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

 P to flip row 1 and 3: 
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

 P to flip row 2 and 3: 
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

 The same can be done for columns! Just do the same thing column wise (eg. flip I[:, 1] and I[:, 2])

 P to flip col 1 and 2: 
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

 P to flip col 1 and 3: 
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

 P to flip col 2 and 3: 
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
