# <font color='green'>QR Factorization</font>

### We'll start off by importing numpy and the linear algebra class (linalg) from numpy

In [1]:
import numpy as np
import numpy.linalg as npla

## QR Factorization Example

### So much easier than doing the Gram-Schmidt Method...!

***Requirement:*** *Any real square matrix A can be factored this way*

In [5]:
A = np.array([[1,2,4],[0,0,5],[0,3,6]])

###########################
# Try these different examples also:
A = np.array([[1,0],[1,4]])
A = np.array([[-1,22,47],[9,-4,154],[0.4,3.3,-6]])
A = np.round(10*np.random.rand(5000,5000))

Q, R = npla.qr(A)

# To set precision of prited outputs:
np.set_printoptions(precision=3)

print("A:\n", A)
print("\nQ:\n", Q,"\nR:\n", R, "\n\nQ@R (compare with matrix A):\n", Q@R , '\n')

print("\nRelative residual norm:", npla.norm(A - Q@R)/npla.norm(A))

A:
 [[ 1.  9.  9. ...  0.  6.  7.]
 [ 7.  1.  6. ...  3.  8.  2.]
 [ 2.  6.  6. ...  5.  0. 10.]
 ...
 [ 0.  2.  3. ...  5.  6.  8.]
 [ 4.  8.  3. ...  2.  8.  1.]
 [ 7.  0.  8. ...  0.  7.  6.]]

Q:
 [[-0.002  0.03  -0.019 ... -0.01   0.01  -0.007]
 [-0.017 -0.016 -0.01  ...  0.002 -0.013  0.006]
 [-0.005  0.017 -0.01  ... -0.002  0.008  0.013]
 ...
 [-0.     0.007 -0.009 ...  0.007  0.002 -0.03 ]
 [-0.01   0.018  0.009 ...  0.01   0.015 -0.005]
 [-0.017 -0.02  -0.02  ... -0.017 -0.019 -0.036]] 
R:
 [[-4.016e+02 -3.047e+02 -3.034e+02 ... -3.043e+02 -3.065e+02 -3.028e+02]
 [ 0.000e+00  2.709e+02  1.156e+02 ...  1.155e+02  1.205e+02  1.186e+02]
 [ 0.000e+00  0.000e+00 -2.464e+02 ... -7.633e+01 -7.731e+01 -7.017e+01]
 ...
 [ 0.000e+00  0.000e+00  0.000e+00 ...  5.773e+00  2.142e+00  6.300e-02]
 [ 0.000e+00  0.000e+00  0.000e+00 ...  0.000e+00 -2.694e+00  5.653e+00]
 [ 0.000e+00  0.000e+00  0.000e+00 ...  0.000e+00  0.000e+00  5.550e+00]] 

Q@R (compare with matrix A):
 [[ 1.000e+00  9.00

## Test for Orthogonality of a Matrix

**Arguments:**

**M**: Input matrix

**tolerance**: (optional) Set tolerance of comparison (ideally, this is zero, but we'll default it to $10^{-8}$)

In [15]:
def ortho(M, tolerance = 1e-8):
    # First, check if M is a square matrix!
    m,n = M.shape
    assert m==n, 'The matrix is not square'
    
    # Check if M is orthogonal by doing this test!
    if np.all( np.abs(M@M.T - np.eye(n)) <= tolerance ):
        print("It's Orthogonal!")
    else:
        print("It's NOT Orthogonal!")


In [8]:
ortho( np.array([ [1,2], [2,1]]) )

In [16]:
ortho(Q)

It's Orthogonal!


In [17]:
ortho(A)
ortho(Q)
ortho(R)

It's NOT Orthogonal!
It's Orthogonal!
It's NOT Orthogonal!
