# <font color="green">Examples of Stability in Matrices</font>

### We'll start off by importing what we need

In [1]:
import numpy as np
import numpy.linalg as npla

***Follows the example done in lecture:***

$$A =
   \left(
   \begin{array}{cc}
    1 & 1000  \\ 	
    0 & 1  \\ 
   \end{array} \right),
    b = \left(
   \begin{array}{c}
    0 & 1  \\ 	\end{array} \right)
$$

Solve for $Ax = b$

In [2]:
A = np.array([ [1, 1000], [0, 1] ])
b_orig = np.array([0, 1])

x_orig = npla.solve(A, b_orig)
# I expect it to be [-1000, 1]

print("x_orig:", x_orig)

print("Make sure. Ax =", A@x_orig, "which should be the same as b =", b_orig)

x_orig: [-1000.     1.]
Make sure. Ax = [0. 1.] which should be the same as b = [0 1]


In [3]:
###########################
# Let's deviate the x-vector by about 0.1%

x_dev = np.array([-999.999, 1.001])

print("x_deviated:", x_dev)

x_deviated: [-999.999    1.001]


In [4]:
###########################
# Now, let's compare the Ax results based on
# Original x-vector vs. Deviated x-vector:

print("b_origin   = A @ x_orig     =", b_orig)     # b_orig
print("b_deviated = A @ x_deviated =", A@x_dev)    # b_dev

print("\nrelative residual norm:", npla.norm(b_orig - A@x_dev)/npla.norm(b_orig))

print("\nCondition number:", npla.cond(A))

b_origin   = A @ x_orig     = [0 1]
b_deviated = A @ x_deviated = [1.001 1.001]

relative residual norm: 1.001000499500241

Condition number: 1000001.9999990001


### <font color='red'>Interestingly, that "little" deviation caused a significant residual!!!</font>

*Is there a way to tell if a matrix is "susceptable" to big outcomes from small changes?*

The "Condition Number" is that indicator: **`npla.cond(A, 'fro')`**

Ideally, you want that to be small (as close to 1 as possible).

In [5]:
###########################
# Condition Number tells the story of stability of Matrix A:

print("\ncondition number of A:",npla.cond(A, 'fro'))


condition number of A: 1000002.0


***Let's try this again with a different matrix:***

$$A =
   \left(
   \begin{array}{cc}
    1 & 9  \\ 	
    9 & 1  \\ 
   \end{array} \right),
    b = \left(
   \begin{array}{c}
    9 & 1  \\ 	\end{array} \right)
$$

Solve for $Ax = b$

In [6]:
A = np.array( [ [1 ,9], [9, 1] ] )
b_orig = np.array([9, 1])

x_orig = npla.solve(A, b_orig)
print("x_orig:", x_orig)

print("condition number of A:",npla.cond(A, 'fro'))

## Try a deviation around 0.1%...
# x_star = np.array([0.001, 1.001])
# b_star = A @ x_star
# print("\nA@x_orig vs. A@x_star =", b_orig, "vs.", b_star)
# print("Rel. residual error =", (npla.norm(b_orig - b_star))/npla.norm(b_orig))

x_orig: [0. 1.]
condition number of A: 2.05


### <font color='red'>Note that the residual was much smaller, as was the condition number of matrix A</font>

*Let's do another one, this time a 3x3:*

In [7]:
A = np.eye(7)
b_orig = np.array([1, 2, 1,1,2,1,1])

x_orig = npla.solve(A, b_orig)
print("x_orig:", x_orig)

x_orig: [1. 2. 1. 1. 2. 1. 1.]


In [ ]:
###########################
# Again, let's deviate just a little bit... 

x_dev = np.array([1.001, 2.002, 1.001,1.001, 2.002, 1.001,1.001])
print("x_deviated:", x_dev)

# Compare Ax vs Ax_dev:
print("\nA @ x_orig:::::", A@x_orig)   # b_orig
print("A @ x_deviated:", A@x_dev)       # b_dev

# What's the relative res. norm?
print("\nrelative residual norm:", npla.norm(b_orig - A@x_dev)/npla.norm(b_orig))

# What's the condition number of matrix A?
print("\ncondition number of A:",npla.cond(A, 'fro'))

x_deviated: [1.001 2.002 1.001 1.001 2.002 1.001 1.001]

A @ x_orig::::: [1. 2. 1. 1. 2. 1. 1.]
A @ x_deviated: [1.001 2.002 1.001 1.001 2.002 1.001 1.001]

relative residual norm: 0.0009999999999998899

condition number of A: 7.000000000000001


In [ ]:
A = np.array([ [0.001, 2, 3], [0.001, 3, 7], [0.001, 2, -1] ])
b = np.array( [0, 0, -1] )

print("A =\n", A, "\n")
print("b =\n", b, "\n")
print("For Ax = b, x =")
x = npla.solve(A,b)
print(x)

x_new = np.array([1250.001, -0.999, 0.24997])
print("x_new =\n", x_new, '\n')

rr = ( (npla.norm (A@x_new - b))/(npla.norm(b)) )
print("Relative residual =", rr)

print("relative")
print("Condition Number of A =", npla.cond(A) )

A =
 [[ 1.e-03  2.e+00  3.e+00]
 [ 1.e-03  3.e+00  7.e+00]
 [ 1.e-03  2.e+00 -1.e+00]] 

b =
 [ 0  0 -1] 

For Ax = b, x =
[ 1.25e+03 -1.00e+00  2.50e-01]
x_new =
 [ 1.250001e+03 -9.990000e-01  2.499700e-01] 

Relative residual = 0.00394544839023375
Condition Number of A = 40854.60279424756
