# <font color="green"> CS111 Lecture 2 - Demo #1 </font>
## <font color="blue"> Spring 2026, Z. Matni </font>

### Basic and Special Matrices in `numpy`
    * Matrix multiplication using the @ operator.
    * Creating random number matrices.
    * Solving for vector x in the Ax = b problem.
    * Finding the residual error and the relative norm of the residual error.
    * Identity, Diagonal Matrices.
    * Matrix slicing.

<em>We'll start off by importing numpy and the linear algebra class (linalg) from numpy</em>

**REMEMBER:** 

<font color="blue">**To execute code inside a grey box, click on that box and then press the "Run" button in the menu bar**,<br>
**OR hit Cntrl-Enter (Windows) or Command-Enter (Mac).**</font>

In [1]:
import numpy as np
import numpy.linalg as npla

*Let's define a matrix in Python!!*

Ok... a vector, really...

In [2]:
A = np.array( [1,2,3] )
print(A)

[1 2 3]


<em>Let's do another one!!!!!!</em>

Let's create:

$$ A = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6 \\
7 & 8 & 9 \\
10 & 11 & -12 \\
\end{bmatrix}$$

In [3]:
# PAY CLOSE ATTENTION TO THE SYNTAX!!!

A = np.array( [ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, -12] ]  )
print(A)

[[  1   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11 -12]]


## <font color="blue"> Multiplying 2 matrices </font>

*Let's define 2 4x4 arrays: U and L, and then we'll multiply them as: A1 = LU*

*Note that this is the same example we did in lecture (on the slides)*

*Also, is it the same as A2 = UL?*

In [4]:
# Example of an upper triangular matrix

U = np.array([ [2,7,1,8],[0,2,8,1],[0,0,8,2],[0,0,0,8] ])
print(U)

[[2 7 1 8]
 [0 2 8 1]
 [0 0 8 2]
 [0 0 0 8]]


In [5]:
# Example of a unit lower triangular matrix

L = np.array([[1,0,0,0],[.5,1,0,0],[0,.5,1,0],[-.5,-.5,0,1]])
print(L)

[[ 1.   0.   0.   0. ]
 [ 0.5  1.   0.   0. ]
 [ 0.   0.5  1.   0. ]
 [-0.5 -0.5  0.   1. ]]


*Ok, we've defined U and L, now let's multiply them (as L.U) and see what we get...*

In [6]:
# The @ operator is matrix multiplication

A1 = L @ U
print(A1)

[[ 2.   7.   1.   8. ]
 [ 1.   5.5  8.5  5. ]
 [ 0.   1.  12.   2.5]
 [-1.  -4.5 -4.5  3.5]]


In [7]:
# Is it the same as A = UL?

A2 = U @ L
print(A2)

[[ 1.5  3.5  1.   8. ]
 [ 0.5  5.5  8.   1. ]
 [-1.   3.   8.   2. ]
 [-4.  -4.   0.   8. ]]


## <font color="blue"> Creating random number matrices </font>

***np.random.rand(N)*** *creates a set of N random numbers in one row*

***np.round()*** *rounds up the numbers to the nearest integer (how could we make them round up to, say the 2nd decimal?)*

In [8]:
print( np.random.rand() )

0.7966836777948423


In [9]:
A = 10*np.random.rand(5)
print(A)

[7.73317351 0.49823089 9.27502382 1.96751344 7.86561363]


In [10]:
print( np.round(A) )

[8. 0. 9. 2. 8.]


In [11]:
# Note the use of .round() and .rand()

MyX = np.round( 10 * np.random.rand(4) )
print(MyX)

[10.  2.  2.  3.]


*Let's try to find the matrix multiplication of A.MyX*

*<font color="red">What limitations do I have?</font>*

In [12]:
# @ operator: matrix multiplication
print( A1, '\n' )
print( MyX, '\n' )
print( A1 @ MyX)

[[ 2.   7.   1.   8. ]
 [ 1.   5.5  8.5  5. ]
 [ 0.   1.  12.   2.5]
 [-1.  -4.5 -4.5  3.5]] 

[10.  2.  2.  3.] 

[ 60.   53.   33.5 -17.5]


In [13]:
# First let's demonstrate a basic use of the print() command:
# Note how the comma in the function call translates to a space being printed:

a = 111
print(a,"hello",3.14,"goodbye")

# You can change the default separator character from ' ' (space char) 
#     to anything you want to like this:
print(a,"hello",3.14,"goodbye", sep='\t')   # \t is the tab char

# You can change the default end-of-print character from '\n' (newline char) 
#     to anything you want to like this:
print(a,"hello",3.14,"goodbye", end='')
print("...no newline in the previous print!!!")

111 hello 3.14 goodbye
111	hello	3.14	goodbye
111 hello 3.14 goodbye...no newline in the previous print!!!


## <font color="blue"> The `.solve()` function </font>

**<font color="red">I am now going to solve for an unknown vector x where: Ax = b</font>**

Notice that I didn't force **b** to be a *column* and that the following code works fine if **b** is defined as a *row* (it's a nice thing that `numpy` does for us!)

For this, I'll be using the `numpy linalg` function:  **solve()**

In [14]:
# Define matrix A and vector b:

A = np.array([[1,1,1],[3,2,1],[1,1,0]])
print(A, "\n")

b = np.array([1,1,1])
print(b)

[[1 1 1]
 [3 2 1]
 [1 1 0]] 

[1 1 1]


In [15]:
# Use the solve() function from npla (np.linalg)
# This solves for x in Ax = b setup

X = npla.solve(A, b)

print(X)

[-1.  2. -0.]


<b><font color="green">How does this compare to the exercise we did on the board?!</font></b>

Here's another example!

In [16]:
# Creating a right-hand side for which we know the answer to Ax=b

A = 20*np.random.rand(5,5)
xorig = np.round(10*np.random.rand(5))

print("A:\n", A)
print("\noriginal x:\n", xorig)

b = A @ xorig
print("\nright-hand side b:\n", b)

A:
 [[ 9.93940138 15.84088676 10.37753684 11.14915711  7.52054174]
 [10.11542812  4.32267732  7.45724925 13.6325681   5.73505137]
 [ 9.99226404 19.66179977 19.63266515  4.45593665  0.26048288]
 [11.86001822  7.57995015 16.45678987  2.88834677  1.16566565]
 [18.76617852 12.22733894 13.05852647 19.86480761 19.68308849]]

original x:
 [8. 4. 4. 5. 5.]

right-hand side b:
 [277.73739966 224.88122853 260.69806971 211.29716788 449.01237026]


*Now*, let's just give Python **A** and **b** and ask it to solve for **x** where **Ax = b**.

Let's then compare what it calculates vs. our own given **x** vector from the previous code above.

In [17]:
x = npla.solve(A,b)

print("computed x:", x)

computed x: [8. 4. 4. 5. 5.]


<font color="blue">So, ARE the *original x* and the *computed x* ***exactly*** the same?</font>

In [18]:
# This is how we can find out if there are any errors in the calculated values (compared to the ideal)
# AND how to assess if these errors are negligible or not (more on that topic later)

#Calculate the RESIDUAL: a vector of the differences between b and A@x:
residual = b - A@x
print("residual:", residual, '\n')

# Calculate norm and relative norm:
print("BETTER METRIC:       norm of the residual::::::", npla.norm(residual))
print("EVEN BETTER METRIC:  relative norm of residual:", npla.norm(residual) / npla.norm(b))

residual: [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 5.68434189e-14] 

BETTER METRIC:       norm of the residual:::::: 5.684341886080802e-14
EVEN BETTER METRIC:  relative norm of residual: 8.550718432770528e-17


<font color="red">END OF THE LECTURE DEMO PART.</font>

# <font color="red"> ***Lab Section Part of the Demo Starts Here***</font>

## <font color="blue"> The `eye()` function </font>

Demonstrating how to create an **<font color="green">IDENTITY MATRIX</font>**, **I**

In [19]:
# Identity matrix
I = np.eye(5)

A = np.array([
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5]
])

print('I:\n', I)
print('\nA:\n', A)
print('\nA.I:\n', A@I)
print('\nI.A:\n', I@A)

I:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

A:
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]

A.I:
 [[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]

I.A:
 [[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


In [34]:
# Let's see if the program can tell us if AI = IA?

print(  A@I == I@A )

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [21]:
# A better way to see this is to boil it down to a single Boolean (True or False):

print(  np.all (A@I == I@A)  )

True


In [22]:
# Yet another way to see this is to see the norm of the matrix (so, one scalar answer):

print( npla.norm(A@I - I@A) )

0.0


## <font color="blue"> The `diag()` function and the `reshape()` function</font>

Demonstrating how to create a **<font color="green">DIAGONAL MATRIX</font>** and how to "reshape" a vector into a matrix.

In [23]:
# Given a vector, you can generate a matrix that has the vector values in its diagonal:
# (comes in handy in later topics in the course)

D = np.diag([2,1,-1,0,-3])
print(D)

[ 2  1 -1  0 -3]


In [24]:
# Let's create a 5x5 matrix from a vector of 25 values (that happen to be the range from 0...24)

v = np.array(range(25))
print(v, '\n\n')

A = v.reshape(5,5)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24] 


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [25]:
# What happens if we multiply D.A ?
print(D@A)

# Note how this multiplies every ROW of A with the corresponding value in D?

[[  0   2   4   6   8]
 [  5   6   7   8   9]
 [-10 -11 -12 -13 -14]
 [  0   0   0   0   0]
 [-60 -63 -66 -69 -72]]


In [41]:
A = np.array([np.ones(3), 2*np.ones(3), 3*np.ones(3)])
b = np.random.rand(3)
print(A)
print(b)
print(np.dot(A,  b))

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
[0.47661169 0.70068376 0.73121968]
[1.90851512 3.81703024 5.72554537]


In [26]:
# What happens if we multiply A.D ?
print(A@D)

# Note how this multiplies every COLUMN of A with the corresponding value in D?

[[  0   1  -2   0 -12]
 [ 10   6  -7   0 -27]
 [ 20  11 -12   0 -42]
 [ 30  16 -17   0 -57]
 [ 40  21 -22   0 -72]]


## <font color="blue"> How to read/write individual elements, rows, columns in matrices</font>

<font color="green">Otherwise known as ***"Matrix Slicing"***</font>

In [27]:
# Change the value of elements (0,0) and (3,4) in matrix A to -10:

A[0,0] = A[3,4]= -10
print(A)

[[-10   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 -10]
 [ 20  21  22  23  24]]


In [28]:
# Print out row 1 only
print( 'row1::::', A[ 1 , : ] )

# Print out column 2 only
print( 'column2:', A[ : , 2 ] )

row1:::: [5 6 7 8 9]
column2: [ 2  7 12 17 22]


In [29]:
# Let's examine and see if we can change the part of the matrix that has 11 12 16 17 values 
#     (it's a sub-matrix that's 2x2):

# Include rows 2 thru 4 (exclusive of 4), and rows 1 thru 3 (exclusive of 3)
#     in other words, rows 2,3 with columns 1,2:
z = A[ 2:4, 1:3 ]
print(z, '\n\n')

A[ 2:4, 1:3 ] = np.array([ [0,0], [0,0] ])
print(A)

[[11 12]
 [16 17]] 


[[-10   1   2   3   4]
 [  5   6   7   8   9]
 [ 10   0   0  13  14]
 [ 15   0   0  18 -10]
 [ 20  21  22  23  24]]


### *end of demo*